### ISSUE TITLE
Cannot gms download or sync down

### ISSUE THREAD

**Issue by abjorck** [thebigmunch/google-music-scripts#1]
Upload works.
Getting the following. Tried on two different systems (albeit same py ver)

[2018-10-28 15:10:22] Logging in to Google Music
[2018-10-28 15:10:23] Loading Google songs
[2018-10-28 15:10:23] Loading local songs
[2018-10-28 15:10:23] Comparing song collections
[2018-10-28 15:10:23] Downloading 2 songs from Google Music
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 11, in <module>
    sys.exit(gms())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 144, in sync_down
    all_includes=all_includes, exclude_filters=exclude_filter, all_excludes=all_excludes
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 169, in do_sync_down
    download_songs(mm, to_download, template=output)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 34, in download_songs
    temp.write(audio)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

**Comment by thebigmunch** [comment]
Thanks for the report.

Looks like I forgot to change the order of a variable assignment when I changed the order of a function return from the google-music package later in development.

``_, audio = mm.download(song)`` in the download_songs function should be ``audio, _ = mm.download(song)``.

**Comment by thebigmunch** [comment]
Forgot to link to this from the [commit](https://github.com/thebigmunch/google-music-scripts/commit/0d6a22d6001570f0865d5182d6c5cc8b2ee474f4#diff-fb84fc272c638f10e4248afea06c136d). Found some things in [google-music-utils](https://github.com/thebigmunch/google-music-utils) that needed fixing along the way. Try out the new release to make sure everything is working as it should.
