### ISSUE TITLE
Add option to send empty sample so ffmpeg/avconv is not needed

### ISSUE THREAD

**Issue by ManuCart** [thebigmunch/google-music-scripts#13]
with 
````
gms upload
````

I have this error

````
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 11, in <module>
    sys.exit(gms())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_music_scripts/commands/upload.py", line 144, in upload
    delete_on_success=delete_on_success
  File "/usr/local/lib/python3.7/site-packages/google_music_scripts/core.py", line 138, in upload_songs
    song, transcode_lossless=transcode_lossless, transcode_lossy=transcode_lossy
  File "/usr/local/lib/python3.7/site-packages/google_music/clients/musicmanager.py", line 270, in upload
    external_art=external_art
  File "/usr/local/lib/python3.7/site-packages/google_music_proto/musicmanager/calls.py", line 334, in generate_sample
    slice_duration=sample_request.challenge_info.duration_millis // 1000, quality='128k'
  File "/usr/local/lib/python3.7/site-packages/google_music_proto/musicmanager/utils.py", line 102, in transcode_to_mp3
    command_path = get_transcoder()
  File "/usr/local/lib/python3.7/site-packages/google_music_proto/musicmanager/utils.py", line 73, in get_transcoder
    f"ffmpeg or avconv must be in the path and support mp3 encoding."
ValueError: ffmpeg or avconv must be in the path and support mp3 encoding.
Details: {transcoder_details}
````

I no want to transcode and no want to install avconv

**Comment by ManuCart** [comment]
Yes, right my MP3 are in 320kbps, and the script need avconv, strange?

**Comment by thebigmunch** [comment]
Google Music's uploading process involves sending them a sample of the file you want to upload for their scan and match feature.

It's possible to send them an empty bytestring for this. gmusicapi does this in an attempt to workaround the scan and match feature altogether, but it's not actually 100% possible as Google can also match on metadata only. Also, if the song's client ID is generated correctly (gmusicapi doesn't), I think they can match on that, too.

So, I could possibly add an option throughout my Google Music packages to just send an empty bytestring instead of an actual sample. But the only sure advantage is to not require ffmpeg/avconv. I'll think about it.
