### ISSUE TITLE
Can't sync up or upload

### ISSUE THREAD

**Issue by gergles** [thebigmunch/google-music-scripts#3]
Attempting to 'sync up' results in the error listed below, and just trying to run 'upload' with a single file (that doesn't already exist in GPM) results in "No songs to upload".

The --verbose option appears to do nothing regarding changing the output, so I can't see what file it's choking on.

```
[~]$ gms sync up --verbose /vol/Music
[2018-11-12 20:18:31] Logging in to Google Music
[2018-11-12 20:18:31] Loading Google songs
[2018-11-12 20:18:37] Loading local songs
[2018-11-12 20:18:37] Comparing song collections
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/gms", line 11, in <module>
    sys.exit(gms())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_scripts/cli.py", line 218, in sync_up
    transcode_lossless=transcode_lossless, transcode_lossy=transcode_lossy
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_scripts/commands.py", line 192, in do_sync_up
    local_songs, google_songs, fields=['artist', 'album', 'title', 'tracknumber'], normalize_values=True
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_utils/compare.py", line 136, in find_missing_items
    normalize_values=normalize_values, normalize_func=normalize_func
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_utils/compare.py", line 32, in _gather_field_values
    item = audio_metadata.load(item).tags  # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/api.py", line 42, in load
    return parser_cls.load(fileobj)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/wav.py", line 73, in load
    duration = audio_size / byte_rate
UnboundLocalError: local variable 'audio_size' referenced before assignment
```

Python version string:
```
Python 3.6.3 (default, Mar 20 2018, 13:50:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
```

I ran the pip install about an hour ago, so should have the most recent version.

**Comment by thebigmunch** [comment]
Thanks for the report.

Looks like I made an editing mistake at some point after testing WAV support in my ``audio-metadata`` library.

If you're comfortable editing your installed Python packages, you can change [this line](https://github.com/thebigmunch/audio-metadata/blob/master/src/audio_metadata/formats/wav.py#L56) in the ``audio-metadata`` package to ``elif subchunk_id == b'data':`` and give it another try.

**Comment by thebigmunch** [comment]
PS There will be some other fixes/updates for WAV file loading as well.

**Comment by gergles** [comment]
Thanks, that did fix that issue. Now, I am encountering a different issue (see below).

Is there any way to make the 'verbose' arg work so that I can identify the files where these errors are occurring?

```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/gms", line 11, in <module>
    sys.exit(gms())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_scripts/cli.py", line 218, in sync_up
    transcode_lossless=transcode_lossless, transcode_lossy=transcode_lossy
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_scripts/commands.py", line 192, in do_sync_up
    local_songs, google_songs, fields=['artist', 'album', 'title', 'tracknumber'], normalize_values=True
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_utils/compare.py", line 136, in find_missing_items
    normalize_values=normalize_values, normalize_func=normalize_func
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_utils/compare.py", line 32, in _gather_field_values
    item = audio_metadata.load(item).tags  # pragma: no cover
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/api.py", line 42, in load
    return parser_cls.load(fileobj)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/mp3.py", line 469, in load
    id3 = ID3v2.load(self._obj)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/id3.py", line 467, in load
    self.tags = ID3v2Frames.load(data, self._header.version, self._header._size)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/id3.py", line 389, in load
    frame = ID3v2Frame.load(data, struct_pattern, size_len, per_byte)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/id3.py", line 344, in load
    return frame_type(*args)
  File "<attrs generated init 08d2734db0467cff404225c962f2647b0a3c550d>", line 3, in __init__
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/audio_metadata/formats/id3.py", line 94, in load
    type = ID3PictureType(data[mime_end + 1])  # noqa
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/enum.py", line 533, in __new__ 
    return cls._missing_(value)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 105 is not a valid ID3PictureType
```

**Comment by thebigmunch** [comment]
Alright, I've released a new version of ``audio-metadata``. I've also released a new version of ``google-music-scripts`` that has updated the required version, so you should just be able to ``pip install -U google-music-scripts`` to try out a proper release.

As for knowing which file, the logging story in this and related packages isn't really finished at this point. These packages need to stabilize a bit before I get too deep into intertwined logging. You can, however, add a ``print(item)`` right above the line in ``google-music-utils`` that is loading the file:
```
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/google_music_utils/compare.py", line 32, in _gather_field_values
    item = audio_metadata.load(item).tags  # pragma: no cover
```

I'd definitely appreciate if you could send that file my way (either post a download link here or email to mail@thebigmunch.me).

**Comment by thebigmunch** [comment]
You can run [this script](https://gist.github.com/thebigmunch/c80560c789ce72d46db301e15c265082) in your music directory. It will recursively try to load music files with ``audio-metadata`` and print the file names of those that fail.

**Comment by thebigmunch** [comment]
Closing due to lack of response.
