### ISSUE TITLE
Errors on large uploads

### ISSUE THREAD

**Issue by ScottESanDiego** [thebigmunch/google-music-scripts#32]
I'm re-uploading my library (yay, artwork!), and find that I get this error ever 6000-ish songs during an `upload`:

```
Traceback (most recent call last):
  File "/data/software/gms/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/commands.py", line 425, in do_upload
    delete_on_success=args.delete_on_success
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/core.py", line 320, in upload_songs
    'FAILURE'
TypeError: log() missing 1 required positional argument: '_message'
```

Re-running the same command works, but typically errors out after about the same number of songs.  I'm running with most things unlimited, but an 8k stack - maybe that's it?  I don't see excessive CPU or memory usage at runtime, and the error isn't intuitive to me.  (It points to...
```logger.log(
                                        'FAILURE'
                                        f"({filenum:>{pad}}/{total}) Failed -- {result['filepath']} | {result['reason']}"
```

...but suspect that's not the actual problem)

The command is `gms upload -v -u ScottESanDiego --album-art folder.jpg /data/media/mp3/Rock` .

**Comment by thebigmunch** [comment]
There is a missing comma after 'FAILUREc on that line. That would fix the error you are getting. And you would get the reason for the failure logged to the console as expected.

**Comment by ScottESanDiego** [comment]
I added the comma (thanks for spotting that), and the error looks like it's an HTTP 502 error from Google not getting caught by GMS:

```Traceback (most recent call last):
  File "/data/software/gms/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/commands.py", line 425, in do_upload
    delete_on_success=args.delete_on_success
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/core.py", line 302, in upload_songs
    no_sample=no_sample
  File "/data/software/gms/lib/python3.6/site-packages/google_music/clients/musicmanager.py", line 302, in upload
    total_uploaded_count=0
  File "/data/software/gms/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/data/software/gms/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/data/software/gms/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/data/software/gms/lib/python3.6/site-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/data/software/gms/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/data/software/gms/lib/python3.6/site-packages/google_music/clients/base.py", line 75, in _call
    response.raise_for_status()
  File "/data/software/gms/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://uploadsj.clients.google.com/uploadsj/scottyagent```

Since it's on the Google side, maybe the way to handle network errors in general would be warn, backoff, and retry?

**Comment by thebigmunch** [comment]
It does get retried up to 10 times. I've never seen a 502 from this call (at least not after 10 retries). gmusicapi also doesn't handle a 502 response, besides the same retrying behavior as in my google-music library. If you could post the file that causes this, that'd be great to see if its something about the file. And I could take a closer look at it.

**Comment by thebigmunch** [comment]
If it's not a specific song causing it, then it'd be hard to test and I'll have to think on how I want to handle it.

**Comment by ScottESanDiego** [comment]
I'm not sure how to recreate it on demand - it's not a specific song, as if I re-run the same sync command it'll sync whatever song failed just fine (and then maybe fail later after ~6000-ish songs).  Hrmph.

My collection is ~36k songs, and this (well, at least the broken FAILURE case before, only had a chance to hit with the fixed log message once so far) happens after ~6000 uploads.

**Comment by thebigmunch** [comment]
To clarify something: [this](https://github.com/thebigmunch/google-music/blob/master/src/google_music/clients/musicmanager.py#L312) is the insane way that Google returns the HTTP status code from this particular call. I *have* seen a 502 from that before that is usually fixed after a retry or two. What I haven't seen is a 502 response from the actual call itself, which is what seems to be happening here. That's what has me surprised. I myself have an even larger collection. And, during testing, I've uploaded 10's of thousands of songs at a time multiple times without ever encountering this.
