### ISSUE TITLE
Error on incompatible file name

### ISSUE THREAD

**Issue by gbowman85** [thebigmunch/google-music-scripts#34]
I was facing an error today when uploading a folder. It was due to a single file.

Here is the error:
Traceback (most recent call last):
File "/usr/local/bin/gms", line 11, in 
sys.exit(run())
File "/usr/local/lib/python3.6/site-packages/google_music_scripts/cli.py", line 920, in run
DISPATCHcommand
File "/usr/local/lib/python3.6/site-packages/google_music_scripts/commands.py", line 329, in do_upload
exclude_globs=args.exclude_globs
File "/usr/local/lib/python3.6/site-packages/google_music_scripts/core.py", line 264, in get_local_songs
with path.open('rb') as f:
File "/usr/local/lib/python3.6/pathlib.py", line 1161, in open
opener=self._opener)
File "/usr/local/lib/python3.6/pathlib.py", line 1015, in _opener
return self.accessor.open(self, flags, mode)
File "/usr/local/lib/python3.6/pathlib.py", line 387, in wrapped
return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/MUSIC/UPLOADS/FabricLive Discography (Albums 31 - 70)/Fabriclive 57 Jackmaster/17 CLS - Can You Feel It? (In House Dub).mp3'

I had real trouble trying to rename or even delete that file, ended up doing it from Windows. I realise that you cannot do anything about the specific file, but it might be an option to catch the error and continue with the rest of the files.

**Comment by thebigmunch** [comment]
This call happens immediately after succeeding an ``is_file`` check which means it exists. Since I already make that check right before opening it and haven't seen another issue like this before, I'm not going to add yet another check to the code for it. Unfortunately, you already renamed or deleted the file, so we can't troubleshoot why it triggered this exception after already succeeding an exist check. Seems like there's nothing special about the filepath on Linux.
