### ISSUE TITLE
Uploading fails due to connection error

### ISSUE THREAD

**Issue by mohammedh123** [thebigmunch/google-music-scripts#39]
Ever since a few days ago, the script has been failing due to connection issues. The stack trace is as follows:

```
[2019-05-14 12:05:35] Logging in to Music Manager
[2019-05-14 12:05:35] Logging in to Mobile Client
[2019-05-14 12:05:36] Loading local songs
[2019-05-14 12:05:36] Comparing hashes
[2019-05-14 12:05:38] Found 0 songs already exist by audio hash
[2019-05-14 12:05:38] Comparing metadata
[2019-05-14 12:05:41] Found 0 songs already exist by metadata
[2019-05-14 12:05:41] Uploading 9 songs to Google Music
Traceback (most recent call last):
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001CFD6D3FC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CFD6D3FC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mohammed\AppData\Local\Programs\Python\Python37\Scripts\gms.exe\__main__.py", line 9, in <module>
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\google_music_scripts\cli.py", line 920, in run
    DISPATCH[command](args)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\google_music_scripts\commands.py", line 425, in do_upload
    delete_on_success=args.delete_on_success
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\google_music_scripts\core.py", line 302, in upload_songs
    no_sample=no_sample
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\google_music\clients\musicmanager.py", line 302, in upload
    total_uploaded_count=0
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\tenacity\__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\google_music\clients\base.py", line 71, in _call
    allow_redirects=call.follow_redirects
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\requests_oauthlib\oauth2_session.py", line 425, in request
    headers=headers, data=data, **kwargs)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\mohammed\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001CFD6D3FC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by thebigmunch** [comment]
A quick Google search for the error you get shows some possibilities. But this is not something from inside my code at all.
