### ISSUE TITLE
Error MAX_LIMIT_REACHED

### ISSUE THREAD

**Issue by ManuCart** [thebigmunch/google-music-scripts#40]
Hi,

I have this error
What's the problem?
````
Follow the prompts and paste provided code: 4/VgFnqoZ6USmcmqO_M-jrPFOJIhSXR5LXVfD4mXF7rEMrvnjCFgTO4nY
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/usr/local/lib/python3.7/site-packages/google_music_scripts/commands.py", line 312, in do_upload
    mm = google_music.musicmanager(args.username, uploader_id=args.uploader_id)
  File "/usr/local/lib/python3.7/site-packages/google_music/api.py", line 51, in musicmanager
    token=token
  File "/usr/local/lib/python3.7/site-packages/google_music/clients/musicmanager.py", line 61, in __init__
    self._upauth(uploader_id, uploader_name)
  File "/usr/local/lib/python3.7/site-packages/google_music/clients/musicmanager.py", line 67, in _upauth
    self._call(mm_calls.UpAuth, uploader_id, uploader_name)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/google_music/clients/base.py", line 79, in _call
    return call.parse_response(response.headers, response.content)
  File "/usr/local/lib/python3.7/site-packages/google_music_proto/musicmanager/models.py", line 42, in parse_response
    raise Exception(f"{self.__class__.__name__} call failed: {res_body}")
Exception: UpAuth call failed: response_type: AUTH_RESPONSE
policy {
  pause_uploads: false
  abort: false
  retry_in_minutes: 5
  bandwidth_cap_kbps: 12000
  pause_downloads: false
  download_bandwidth_cap_kbps: 16000
  send_analytics: false
  enable_gapless: true
  enable_m4p: true
}
auth_status: MAX_LIMIT_REACHED
auth_error: false
upauth_response {
  uploader_id: "B8:27:EB:E6:FE:B7-2"
}
````

**Comment by thebigmunch** [comment]
It means the limit for authenticated devices on the account has been reached.

**Comment by ManuCart** [comment]
Hi, thank you for your help.
I deleted some devices on now it's working
