### ISSUE TITLE
GMS stopped working today. Error message attached.

### ISSUE THREAD

**Issue by jrp13149** [thebigmunch/google-music-scripts#41]
I don't really know what to make of this. Any suggestions for next step diagnostics?

Thanks,

Jeff.

> [2019-06-24 13:14:41] Loading local songs
[2019-06-24 13:14:41] Comparing metadata
[2019-06-24 13:15:07] Found 0 songs already exist by metadata
[2019-06-24 13:15:07] Uploading 3 songs to Google Music
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/genesis/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/miniconda3/envs/genesis/lib/python3.6/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/usr/local/miniconda3/envs/genesis/lib/python3.6/site-packages/google_music_scripts/commands.py", line 425, in do_upload
    delete_on_success=args.delete_on_success
  File "/usr/local/miniconda3/envs/genesis/lib/python3.6/site-packages/google_music_scripts/core.py", line 320, in upload_songs
    'FAILURE'
TypeError: log() missing 1 required positional argument: '_message'

**Comment by thebigmunch** [comment]
This should actually be fixed in the master branch, just haven't made a release since fixing it. Use ``pip install -U git+https://github.com/thebigmunch/google-music-scripts`` to install it from git to try it out. Keep in mind that the verbosity levels have been reworked, so the default output will be different.

**Comment by jrp13149** [comment]
This worked, thanks!
