### ISSUE TITLE
Error 400 uploading songs

### ISSUE THREAD

**Issue by jason-a69** [thebigmunch/google-music-scripts#43]
Hi there, 

When I try and upload music, I get these errors

```
[2019-07-30 13:12:05] Loading local songs
[2019-07-30 13:12:08] Comparing hashes
[2019-07-30 13:12:08] Loading Google songs with MobileClient
[2019-07-30 13:12:23] Comparing metadata
[2019-07-30 13:12:23] Loading Google songs with MusicManager
[2019-07-30 13:13:28] Sorting songs
[2019-07-30 13:13:28] Uploading songs
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/google_music_scripts/cli.py", line 968, in run
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/google_music_scripts/commands.py", line 464, in do_upload
    delete_on_success=args.delete_on_success
  File "/usr/local/lib/python3.6/site-packages/google_music_scripts/core.py", line 334, in upload_songs
    no_sample=no_sample
  File "/usr/local/lib/python3.6/site-packages/google_music/clients/musicmanager.py", line 302, in upload
    total_uploaded_count=0
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/google_music/clients/base.py", line 75, in _call
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://uploadsj.clients.google.com/uploadsj/scottyagent
```

Version:-
`gms -V`
google-music-scripts 4.1.1

Check I can log in:-
`gms quota -v`

```
[2019-07-30 15:07:33] Logging in to Music Manager
[2019-07-30 15:07:35] Quota -- 20887/100000 (20.89%)
[2019-07-30 15:07:35] All done!
```

Any advice please?

Thanks

Jason

**Comment by thebigmunch** [comment]
Google's servers are notoriously flaky at times. This could just be a one-time or temporary thing. If it continutes, I'd try uploading smaller batches of files if you weren't already to determine if it is a specific file that triggers it or just random.

**Comment by thebigmunch** [comment]
You can also increase the verbosity (``-vv``) to see any progress that is actually made with the upload.

**Comment by thebigmunch** [comment]
Alright, so I re-added progress messages to downloading/uploading in google-music-scripts at the trace log level. You can pip install -U git+https://github.com/thebigmunch/google-music-scripts and run the command with -vvvv to see which file is being uploaded.

**Comment by jason-a69** [comment]
I had managed to track down the song causing the issue but I am updating gsm and will then use -vvv to track the progress in future. Thanks very much for your help.

**Comment by thebigmunch** [comment]
I'd actually like to get that song for testing to see if it consistently causes an issue and why.

**Comment by jason-a69** [comment]
I had managed to track down the song causing the issue but I am updating gsm and will then use -vvv to track the progress in future. Thanks very much for your help.

> 
> 
> I'd actually like to get that song for testing to see if it consistently causes an issue and why.

It's attached :)


[1-02 No Diggity.zip](https://github.com/thebigmunch/google-music-scripts/files/3446647/1-02.No.Diggity.zip)

**Comment by thebigmunch** [comment]
So, I'm pretty sure the reason it was causing a problem is that the embedded cover art. I've [encountered issues](https://github.com/thebigmunch/google-music-proto/issues/4) with it before, but have never been able to find the exact cause/specs that work. Once I removed the album art from the file, it uploaded just fine.

**Comment by jason-a69** [comment]
I had managed to track down the song causing the issue but I am updating gsm and will then use -vvv to track the progress in future. Thanks very much for your help.

> 
> 
> I'd actually like to get that song for testing to see if it consistently causes an issue and why.

It's attached :)



> 
> 
> So, I'm pretty sure the reason it was causing a problem is that the embedded cover art. I've [encountered issues](https://github.com/thebigmunch/google-music-proto/issues/4) with it before, but have never been able to find the exact cause/specs that work. Once I removed the album art from the file, it uploaded just fine.

I have tracks as part of the same album with the same cover art that upload just fine.

**Comment by thebigmunch** [comment]
Yeah, as I said in my comment and more in the linked issue, there doesn't seem to be a consistency to it. 

> It doesn't seem to be based on resolution nor file size. And, during testing there were times when these files were actually accepted.

Weird things happen on Google's servers ^_^ But removing the art for these files seems to always allow an upload.
