### ISSUE TITLE
requests.exceptions.HTTPError ?

### ISSUE THREAD

**Issue by nemonein** [thebigmunch/google-music-scripts#46]
Hello.
I would like to thank you for your great effort.

I've installed gms on Ubuntu 18.04 (using Pip3, version 4.1.1
) , and I've got these messages.

```
$ gms search -f 'artist[keats]'
[2019-09-27 18:55:12] Logging in to Mobile Client
Visit:

https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=228293309116.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fskyjam&state=XIVBuVoRskjUF4MU8QtlO14gFuOLSA&access_type=offline&prompt=select_account

Follow the prompts and paste provided code:  (code from Google)

[2019-09-27 18:55:45] Loading Google songs with MobileClient
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 968, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 281, in do_search
    search_results = get_google_songs(mc, filters=args.filters)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 233, in get_google_songs
    google_songs = client.songs()
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/mobileclient.py", line 1694, in songs
    for chunk in self.songs_iter(page_size=49995):
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/mobileclient.py", line 1718, in songs_iter
    start_token=start_token
  File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/base.py", line 76, in _call
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mclients.googleapis.com/sj/v2.5/trackfeed?hl=en_US&tier=fr&alt=json&dv=0&updated-min=-1
```
After I pasted the code (from Google), but all I got was the error message.
And, `~/.config/google-music-scripts/google-music-scripts.toml` has nothing. File size is 0.

Any suggestion would be appreciated.

**Comment by thebigmunch** [comment]
A 500 error may just be a particular Google Music server being flaky. It happens. Try again after some time and let me know if it still occurs. I just did the same without issue.

**Comment by nemonein** [comment]
Thank you for your quick answer.
I'll try it later, and let you know.

Besides, I have a question.
After pasting the provided code, I think gms should be on the [3rd party apps](https://support.google.com/accounts/answer/3466521?hl=en) list.
I also use [gcalcli](https://github.com/insanum/gcalcli), and I confirm that is on the list.
However I could not find gms on it.
Could this be the reason for the error?

**Comment by thebigmunch** [comment]
No. Unlike Google Calendar, there is not a public API for Google Music. So, my Google Music library clients have to pose as Google's own clients. That means they shouldn't be picked up as 3rd-party.

**Comment by nemonein** [comment]
I tried quite a few times, but the result is the same.
I do have Keats in my google music library, which was uploaded by Google's [music manager](https://play.google.com/music/listen?u=0#/manager).

**Comment by thebigmunch** [comment]
Whoops. Got busy and forgot about this for a bit. Just curious, have you used the Google Music mobile app with the account before?

**Comment by nemonein** [comment]
Yes, I'm using Google play music app on my Android phone.

**Comment by kevinchg** [comment]
I also faced this issue in couple hours ago, exactly the same.
