### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx.middleware.basic_auth'; 'httpx.middleware' is not a package

### ISSUE THREAD

**Issue by geezuh** [thebigmunch/google-music-scripts#48]
Traceback (most recent call last):                                                                                             │················
  File "/home/gzuh/.local/bin/gms", line 6, in <module>                                                                        │················
    from google_music_scripts.cli import run                                                                                   │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music_scripts/cli.py", line 26, in <module>                       │················
    from .commands import (                                                                                                    │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music_scripts/commands.py", line 3, in <module>                   │················
    import google_music                                                                                                        │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music/__init__.py", line 2, in <module>                           │················
    from .api import *                                                                                                         │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music/api.py", line 6, in <module>                                │················
    from .clients import MobileClient, MusicManager                                                                            │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music/clients/__init__.py", line 1, in <module>                   │················
    from .mobileclient import *                                                                                                │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music/clients/mobileclient.py", line 18, in <module>              │················
    from .base import GoogleMusicClient                                                                                        │················
  File "/home/gzuh/.local/lib/python3.8/site-packages/google_music/clients/base.py", line 8, in <module>                       │················
    from httpx.middleware.basic_auth import BasicAuthMiddleware as HTTPBasicAuth                                               │················
ModuleNotFoundError: No module named 'httpx.middleware.basic_auth'; 'httpx.middleware' is not a package

**Comment by sn0rlax** [comment]
Just reporting in with the exact same error.

**Comment by thebigmunch** [comment]
See https://github.com/thebigmunch/google-music/issues/12. ``pip install httpx==0.7.8`` will fix things for you.
