### ISSUE TITLE
gms upload: TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by pffpcds** [thebigmunch/google-music-scripts#49]
Recently when trying to perform "gms upload" I am presented with this error when using differing sets of mp3s where both sets play fine locally:

gms upload -vv
[2020-02-08 22:20:20] Logging in to Music Manager
[2020-02-08 22:20:21] Logging in to Mobile Client
[2020-02-08 22:20:21] Loading local songs
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 389, in do_upload
    exclude_globs=args.exclude_globs
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 209, in get_local_songs
    exclude_globs=exclude_globs
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 211, in <listcomp>
    if audio_metadata.determine_format(filepath) is not None
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/api.py", line 71, in determine_format
    return MP3 if _verify_mp3(data) else None
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/api.py", line 41, in _verify_mp3
    MP3StreamInfo.find_mpeg_frames(data)
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/formats/mp3.py", line 551, in find_mpeg_frames
    frame = MPEGFrameHeader.load(data)
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/utils.py", line 59, in datareader
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/audio_metadata/formats/mp3.py", line 430, in load
    data.read(1),
  File "/usr/local/lib/python3.6/dist-packages/bitstruct.py", line 523, in unpack
    return CompiledFormat(fmt).unpack(data)
  File "/usr/local/lib/python3.6/dist-packages/bitstruct.py", line 401, in unpack
    return self.unpack_from(data)
  File "/usr/local/lib/python3.6/dist-packages/bitstruct.py", line 422, in unpack_from
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/usr/local/lib/python3.6/dist-packages/bitstruct.py", line 422, in <listcomp>
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/usr/local/lib/python3.6/dist-packages/bitstruct.py", line 302, in unpack_from_any
    len(bits)))
TypeError: 'tuple' object is not callable

**Comment by thebigmunch** [comment]
You can run the command with different verbosity levels. Running with ``-vvv`` should let you know which file is causing the issue. I'd need to have that file to check to see what is happening.

**Comment by thebigmunch** [comment]
Scratch that. I wasn't paying attention. The exception is of course happening before the uploading stage.

You can use [this script](https://gist.github.com/thebigmunch/c80560c789ce72d46db301e15c265082) in that directory to find all files that won't load with my ``audio-metadata`` library. Please post one here or through email for me to look at.

**Comment by pffpcds** [comment]
For one of the directories it appears this was caused by the ._ files created by macOS on the network storage (SMB share accessed by macOS but uploads are done via Ubuntu through NFS mount). Running amtest.py received this error when trying to load the ._ (e.g. ._SongName.mp3) files:

Could not determine format: ._SongName.mp3

After removing those files the upload proceeded as normal in one folder.

However on the second folder I am receiving a different error after removing the ._ files:  

[2020-02-09 20:17:40] Uploading songs
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 483, in do_upload
    delete_on_success=args.delete_on_success
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 251, in upload_songs
    no_sample=no_sample
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/musicmanager.py", line 269, in upload
    track_info = mm_calls.Metadata.get_track_info(song)
  File "/usr/local/lib/python3.6/dist-packages/google_music_proto/musicmanager/calls.py", line 269, in get_track_info
    date = metadata.tags.date[0]
IndexError: list index out of range

amtest.py has no output for this folder.

Let me know if you need the files or would like me to create a new issue for this.  Thanks thebigmunch!

**Comment by thebigmunch** [comment]
Yeah. You can do ``pip install -U git+https://github.com/thebigmunch/google-music-scripts`` to install the fix I talked about earlier so you can use ``-vvvvv`` to find the song causing this issue. I'd be interested in seeing how it is getting a date field in the tags without a value.

**Comment by thebigmunch** [comment]
I would've liked to see those other files, so I could potentially handle that case better.

**Comment by pffpcds** [comment]
If you need the files themselves I can send them, but they're metadata files created by macOS. They are created when copying to network shares to retain the metadata over differing filesystems. For example:

$ cat ._01SomeSong.mp3 
Mac OS X        	2??ATTR?d??[?Hcom.apple.macl?com.apple.quarantine??????H1?(WSkN2?0082;5e3f3157;Keka;This resource fork intentionally left blank   ??

or

$ cat ._02SomeSong..mp3 
Mac OS X        	2??ATTR?n??H?Hcom.apple.macl??????H1?(WSkN2?This resource fork intentionally left blank   ??

**Comment by pffpcds** [comment]
Here is the output and file for the failing upload:

$ gms upload -vvvvv
[2020-02-09 21:02:42] Logging in to Music Manager
[2020-02-09 21:02:42] Logging in to Mobile Client
[2020-02-09 21:02:42] Loading local songs
[2020-02-09 21:02:42] Found 1 local songs
[2020-02-09 21:02:42] Comparing hashes
[2020-02-09 21:02:42] Loading Google songs with MobileClient
[2020-02-09 21:02:50] Found 19496 Google songs with MobileClient
[2020-02-09 21:02:50] Found 0 songs already exist by audio hash
[2020-02-09 21:02:50] Comparing metadata
[2020-02-09 21:02:50] Loading Google songs with MusicManager
[2020-02-09 21:03:01] Found 19496 Google songs with MusicManager
[2020-02-09 21:03:02] Found 0 songs already exist by metadata
[2020-02-09 21:03:02] Sorting songs
[2020-02-09 21:03:02] Found 1 songs to upload
[2020-02-09 21:03:02] Uploading songs
[2020-02-09 21:03:02] Uploading -- /home/user/server/what/01ThisSong.mp3
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 483, in do_upload
    delete_on_success=args.delete_on_success
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 251, in upload_songs
    no_sample=no_sample
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/musicmanager.py", line 269, in upload
    track_info = mm_calls.Metadata.get_track_info(song)
  File "/usr/local/lib/python3.6/dist-packages/google_music_proto/musicmanager/calls.py", line 269, in get_track_info
    date = metadata.tags.date[0]
IndexError: list index out of range


[01ThisSong.mp3.zip](https://github.com/thebigmunch/google-music-scripts/files/4177832/01ThisSong.mp3.zip)

**Comment by thebigmunch** [comment]
So, the problem with that file is that it has an ID3v2.3 header, but the year is in a ``TDRC`` frame, which is ID3v2.4-only. The format of ``TDRC`` is slightly different than the ID3v2.3 ``TYER`` frame, one is null-terminated while the other isn't allowed to be. I should definitely be handling cases like this in my ``audio-metadata`` library the same as it handles other invalid frames (it ignores them). My advice to you is to use tagging software to fix it to use the proper ID3v2.3 frame (probably just by entering and/or saving it) or upgrade it to ID3v2.4.
