### ISSUE TITLE
Error when deleting songs

### ISSUE THREAD

**Issue by magneticflux-** [thebigmunch/google-music-scripts#50]
Seems like the library was updated and it renamed `song_delete` to `songs_delete`.

Log:
```
Traceback (most recent call last):
  File "/home/mitchell/.pyenv/versions/3.8.1/bin/gms", line 8, in <module>
    sys.exit(run())
  File "/home/mitchell/.pyenv/versions/3.8.1/lib/python3.8/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/home/mitchell/.pyenv/versions/3.8.1/lib/python3.8/site-packages/google_music_scripts/commands.py", line 71, in do_delete
    mc.song_delete(song)
AttributeError: 'MobileClient' object has no attribute 'song_delete'
```

**Comment by thebigmunch** [comment]
Thanks for the report. This will be in the next release.
