### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by arnold-maderthaner** [thebigmunch/google-music-scripts#52]
Hi !

I'm trying to add new files to my exisisting Google music library but I get the following stack trace:

[2020-03-12 19:59:35] Comparing hashes
[2020-03-12 19:59:35] Loading Google songs with MobileClient
[2020-03-12 19:59:43] Comparing metadata
[2020-03-12 19:59:43] Loading Google songs with MusicManager
[2020-03-12 19:59:57] Sorting songs
[2020-03-12 19:59:57] Uploading songs
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/commands.py", line 493, in do_upload
    delete_on_success=args.delete_on_success
  File "/usr/local/lib/python3.6/dist-packages/google_music_scripts/core.py", line 241, in upload_songs
    no_sample=no_sample
  File "/usr/local/lib/python3.6/dist-packages/google_music/clients/musicmanager.py", line 269, in upload
    track_info = mm_calls.Metadata.get_track_info(song)
  File "/usr/local/lib/python3.6/dist-packages/google_music_proto/musicmanager/calls.py", line 274, in get_track_info
    date = metadata.tags.date[0]
IndexError: list index out of range

**Comment by thebigmunch** [comment]
If you run it with ``-vvvvv``, you'll be able to find which file is causing this. I'd appreciate if you could post it here or send it by email so I can take a look at it. The solution either way will be to add a try/except in ``google-music-proto``, which is where I'm transferring this issue. But it'd be nice to see what is causing that empty tag value.
