### ISSUE TITLE
Exceptions from mm.upload should be caught 

### ISSUE THREAD

**Issue by iiegn** [thebigmunch/google-music-scripts#55]
`mm.upload(...)` can raise exceptions on single file upload. Unfortunately, the whole queue gets dumped when this happens...
https://github.com/thebigmunch/google-music-scripts/blob/91247bb208f4689f7b973eaa88e0315254dc3fd4/src/google_music_scripts/core.py#L238
This should be caught similarly to the [`mm.download(...)`](https://github.com/thebigmunch/google-music-scripts/blob/91247bb208f4689f7b973eaa88e0315254dc3fd4/src/google_music_scripts/core.py#L39)

**Comment by thebigmunch** [comment]
What exception is happening?

**Comment by iiegn** [comment]
the trace looks like this:
```
  File ".../versions/3.8.2/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

  File ".../versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
urllib3.exceptions.MaxRetryError: : HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent?...&file_id=000 (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

  File ".../versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_utils.py", line 368, in as_network_error                                                                                                         
    raise NetworkError(exc) from exc
httpx._exceptions.NetworkError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent?...&file_id=000 (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))                                                                                     ```
As far as I can see, this happened with different files. (`try-excepting` the block solved the problem after 2 runs; although, in the last run there was still one file that failed with this error - albeit seemingly having proper data and metadata)

**Comment by thebigmunch** [comment]
Is that the entire traceback? I don't see the call site from any of my libraries. I would actually help me figure out if other things need to be guarded.

**Comment by iiegn** [comment]
I tried to generate a new one, but all my songs had been uploaded. I added a few songs and they were all uploaded successfully... Eventually, I was lucky and could get a traceback from a running terminal session:
(just-in-case: sanitized `upload_id=...`)
```
[2020-04-10 03:47:41] Uploading songs
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 1043, in _send_output
    self.send(chunk)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/http/client.py", line 965, in send
    self.sock.sendall(data)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_utils.py", line 364, in as_network_error
    yield
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_dispatch/urllib3.py", line 98, in send
    conn = self.pool.urlopen(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent?upload_id=...&file_id=000 (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/gms-3.8.2/bin/gms", line 11, in <module>
    load_entry_point('google-music-scripts', 'console_scripts', 'gms')()
  File "/root/google-music-scripts/src/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/root/google-music-scripts/src/google_music_scripts/commands.py", line 488, in do_upload
    upload_songs(
  File "/root/google-music-scripts/src/google_music_scripts/core.py", line 238, in upload_songs
    result = mm.upload(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/google_music/clients/musicmanager.py", line 408, in upload
    upload_response = self._call(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/tenacity/__init__.py", line 311, in wrapped_f
    return self.call(f, *args, **kw)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/tenacity/__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/tenacity/__init__.py", line 350, in iter
    raise retry_exc.reraise()
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/tenacity/__init__.py", line 168, in reraise
    raise self.last_attempt.result()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/tenacity/__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/google_music/clients/base.py", line 80, in _call
    response = self._session.request(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/google_music/sessions.py", line 147, in request
    return super().request(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_client.py", line 570, in request
    return self.send(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_client.py", line 590, in send
    response = self.send_handling_redirects(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_client.py", line 617, in send_handling_redirects
    response = self.send_handling_auth(
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_client.py", line 654, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_client.py", line 678, in send_single_request
    response = dispatcher.send(request, timeout=timeout)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_dispatch/urllib3.py", line 98, in send
    conn = self.pool.urlopen(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.pyenv/versions/3.8.2/envs/gms-3.8.2/lib/python3.8/site-packages/httpx/_utils.py", line 368, in as_network_error
    raise NetworkError(exc) from exc
httpx._exceptions.NetworkError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent?upload_id=...&file_id=000 (Caused by ProtocolError('Connection aborted.', BrokenPipeError(32, 'Broken pipe')))
```
