### ISSUE TITLE
Using created-after results in "unsupported operand type(s) for /: 'str' and 'int' "

### ISSUE THREAD

**Issue by pjft** [thebigmunch/google-music-scripts#57]
Hi. Apologies for creating this here, and let me know if there's any more details I can provide.

Running google-music-scripts 4.5.0 on Raspbian, using Python 3.7.

The command `gms download -n --created-after 2019` (or other dates with months, days, etc) seems to result consistently in:

```
Traceback (most recent call last):
  File "/home/pi/.local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_scripts/commands.py", line 140, in do_download
    modification_dates=modification_dates,
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_scripts/core.py", line 104, in filter_google_dates
    return list(matched_songs)
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_scripts/core.py", line 86, in <genexpr>
    if _dt_from_gm_timestamp(song['creationTimestamp']) in period
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_scripts/core.py", line 80, in _dt_from_gm_timestamp
    return pendulum.from_timestamp(gm_utils.from_gm_timestamp(gm_timestamp))
  File "/home/pi/.local/lib/python3.7/site-packages/google_music_utils/metadata.py", line 28, in from_gm_timestamp
    return int(timestamp / 1000000)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

Removing that option does work and download things. It might be a locale thing, but I am unsure of how to further troubleshoot to narrow down the issue.

Let me know how I can help.

**Comment by thebigmunch** [comment]
It's not a locale issue. Apparently not many people use the date options as the cause of this was introduced quite some time ago. I'll have a fix for this later today (will be in the google-music-utils library).

If you didn't want to wait, you can change the [following line](https://github.com/thebigmunch/google-music-utils/blob/master/src/google_music_utils/metadata.py#L28) in your installed google-music-utils to ``return int(timestamp) // 1000000``.

**Comment by pjft** [comment]
Wow - thanks for the quick response. I'll look into it later today or tomorrow when I'm at my computer.

Thank you for putting this project together - I was very much looking for a backup/sync solution for my Play Music library to my NAS, and this seems to work great!
