### ISSUE TITLE
gms download: TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by priccis** [thebigmunch/google-music-scripts#58]
Amid the end of Google Music I wanted to download my songs, which were all uploaded using this same excellent tool.

The problem is related to this https://github.com/thebigmunch/google-music-scripts/issues/49#issuecomment-583897400 but in this case the offending files are on google's server, so I cannot edit their tags.

I'm running this command:
`gms down -vvvv -o "%artist%/%album%/%track2% - %title%"`

I get multiple of this:
```
AudioMetadataWarning:
    Ignoring ``TYER``.
    Year frame values must be 4-character number strings.
```
And then this error:
```
[2020-05-14 22:55:40] Downloading songs from Google Music
Traceback (most recent call last):
  File "/mnt/volume_sfo3_01/venv/bin/gms", line 11, in <module>
    sys.exit(run())
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/google_music_scripts/commands.py", line 263, in do_download
    download_songs(mm, to_download, template=args.output)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/google_music_scripts/core.py", line 51, in download_songs
    tags = audio_metadata.loads(audio).tags
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/audio_metadata/api.py", line 145, in loads
    parser_cls = determine_format(data)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/audio_metadata/api.py", line 78, in determine_format
    MP3StreamInfo.find_mpeg_frames(data)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/wrapt/wrappers.py", line 625, in __call__
    kwargs)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/tbm_utils/decorators.py", line 44, in wrapper
    return wrapped(*args, **kwargs)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/audio_metadata/formats/mp3.py", line 574, in find_mpeg_frames
    frame = MPEGFrameHeader.parse(data)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/wrapt/wrappers.py", line 625, in __call__
    kwargs)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/tbm_utils/decorators.py", line 44, in wrapper
    return wrapped(*args, **kwargs)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/audio_metadata/formats/mp3.py", line 434, in parse
    data.read(2),
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/bitstruct/__init__.py", line 522, in unpack
    return CompiledFormat(fmt).unpack(data)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/bitstruct/__init__.py", line 400, in unpack
    return self.unpack_from(data)
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/bitstruct/__init__.py", line 421, in unpack_from
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/bitstruct/__init__.py", line 421, in <listcomp>
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/mnt/volume_sfo3_01/venv/lib/python3.6/site-packages/bitstruct/__init__.py", line 301, in unpack_from_any
    len(bits)))
TypeError: 'tuple' object is not callable
```
Thanks

**Comment by thebigmunch** [comment]
> offending files are on google's server, so I cannot edit their tags.

You should be able to edit the metadata on Google Music. Unless you're talking about a purchased song, then I'm not sure whether you can do that or not.

As for the exception, you can add another ``v`` to see what song it's trying to download that causes it. To actually get the file for me to test, you could change [this code](https://github.com/thebigmunch/google-music-scripts/blob/master/src/google_music_scripts/core.py#L51-L68) to this:

``` python
try:
	tags = audio_metadata.loads(audio).tags
except:
	p = Path(f"test-file-{songnum}.mp3").resolve()
	p.write_bytes(audio)
	print(f"Writing failed file to: {p}")
else:
	filepath = gm_utils.template_to_filepath(template, tags).with_suffix('.mp3')
	if filepath.is_file():
		filepath.unlink()
	
	filepath.parent.mkdir(parents=True, exist_ok=True)
	filepath.touch()
	filepath.write_bytes(audio)
	
	logger.log(
		'ACTION_SUCCESS',
		"({:>{}}/{}) Downloaded -- {} ({})",
		songnum,
		pad,
		total,
		filepath,
		song['id']
	)
```

That will write the file to disk when it fails, so you can attach it here or email it to me.

**Comment by adriel** [comment]
I also get a stack of `Ignoring ``TYER``.` messages. But it seems to still download the song, so I'm not to worried. What is "TYER"?

**Comment by thebigmunch** [comment]
> I also get a stack of `` Ignoring ``TYER``. `` messages. But it seems to still download the song, so I'm not too worried. What is "TYER"?

``TYER`` is the ID3v2.3 frame. According to the spec, it should only contain a 4-digit year. But a lot of people put full dates in it. That message is warning you that you have an non-compliant value.

**Comment by thebigmunch** [comment]
> `TYER` is the ID3v2.3 frame. According to the spec, it should only contain a 4-digit year. But a lot of people put full dates in it. That message is warning you that you have a non-compliant value.

When I added these warnings to audio-metadata, I probably should've had google-music-scripts silence them. They don't really help in the context of its functionality. Will do that for the next release.

**Comment by thebigmunch** [comment]
@priccis I'm still interested in getting the file for testing. I'll be adding a try/except that will avoid the exception and ignore the song that causes it. Not the ideal if the file is indeed a valid file.

**Comment by priccis** [comment]
Thanks for your fast, and sorry for my late, response.
This is the file I got, which only is 445 bytes
[test-file-1.mp3.zip](https://github.com/thebigmunch/google-music-scripts/files/4669882/test-file-1.mp3.zip)

**Comment by priccis** [comment]
> Thanks for your fast, and sorry for my late, response.
> This is the file I got, which only is 445 bytes
> [test-file-1.mp3.zip](https://github.com/thebigmunch/google-music-scripts/files/4669882/test-file-1.mp3.zip)

Actually, that particular song (Miss You by The Rolling Stones) wont't play in Google Music! It's corrupted. A message pops up in the Android's client: "Couldn't play the track that you requested".

**Comment by aenertia** [comment]
I am getting this for any down operation regardless of filter at this point (mid july) am trying to get my library out so I can exit the service prior to the forced shutdown and move to YTM.
```

[aenertia@kiorewha gmusic]$ gms download -f 'artist[Daft Punk]'
[2020-07-17 10:08:27] Logging in to Music Manager
[2020-07-17 10:08:27] Logging in to Mobile Client
[2020-07-17 10:08:28] Loading Google songs with MusicManager
[2020-07-17 10:08:29] Filtering songs by metadata
[2020-07-17 10:08:29] Loading Google songs with MobileClient
[2020-07-17 10:08:36] Filtering songs by metadata
[2020-07-17 10:08:36] Loading local songs
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.8/site-packages/google_music_scripts/commands.py", line 143, in do_download
    local_songs = get_local_songs(
  File "/usr/local/lib/python3.8/site-packages/google_music_scripts/core.py", line 186, in get_local_songs
    local_songs = [
  File "/usr/local/lib/python3.8/site-packages/google_music_scripts/core.py", line 195, in <listcomp>
    if audio_metadata.determine_format(filepath) in [
  File "/usr/local/lib/python3.8/site-packages/audio_metadata/api.py", line 78, in determine_format
    MP3StreamInfo.find_mpeg_frames(data)
  File "/usr/local/lib/python3.8/site-packages/wrapt/wrappers.py", line 624, in __call__
    return self._self_wrapper(self.__wrapped__, instance, args,
  File "/usr/local/lib/python3.8/site-packages/tbm_utils/decorators.py", line 44, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/audio_metadata/formats/mp3.py", line 574, in find_mpeg_frames
    frame = MPEGFrameHeader.parse(data)
  File "/usr/local/lib/python3.8/site-packages/wrapt/wrappers.py", line 624, in __call__
    return self._self_wrapper(self.__wrapped__, instance, args,
  File "/usr/local/lib/python3.8/site-packages/tbm_utils/decorators.py", line 44, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/audio_metadata/formats/mp3.py", line 432, in parse
    sync, version_id, layer_index, protection = bitstruct.unpack(
  File "/usr/local/lib/python3.8/site-packages/bitstruct/__init__.py", line 522, in unpack
    return CompiledFormat(fmt).unpack(data)
  File "/usr/local/lib/python3.8/site-packages/bitstruct/__init__.py", line 400, in unpack
    return self.unpack_from(data)
  File "/usr/local/lib/python3.8/site-packages/bitstruct/__init__.py", line 421, in unpack_from
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/usr/local/lib/python3.8/site-packages/bitstruct/__init__.py", line 421, in <listcomp>
    return tuple([v[1] for v in self.unpack_from_any(data, offset)])
  File "/usr/local/lib/python3.8/site-packages/bitstruct/__init__.py", line 298, in unpack_from_any
    raise Error(
TypeError: 'tuple' object is not callable
[aenertia@kiorewha gmusic]$ 

```
